// Master list of every podcast the sheet mentions, with the status implied by
// the section it sits in. Names are the sheet's wording; `q` is the search term
// used to find the real feed when the sheet's label is ambiguous or abbreviated.
export const PODCASTS = [
  // ---- Weekly tab: "Already Doing" ----
  { name: "18Forty - Exploring Big Jewish Ideas", status: "Doing", slot: "Weekly", q: "18Forty Podcast" },
  { name: "Honestly with Bari Weiss", status: "Doing", slot: "Weekly", q: "Honestly with Bari Weiss" },
  { name: "Behind the Bima", status: "Doing", slot: "Weekly", q: "Behind the Bima" },
  { name: "Business Wars", status: "Doing", slot: "Weekly", q: "Business Wars" },
  { name: "Freakonomics Radio", status: "Doing", slot: "Weekly", q: "Freakonomics Radio" },
  { name: "Jews You Should Know", status: "Doing", slot: "Weekly", q: "Jews You Should Know" },
  { name: "Life Kit", status: "Doing", slot: "Weekly", q: "Life Kit NPR", note: "Sheet: considering stopping" },
  { name: "No Stupid Questions", status: "Doing", slot: "Weekly", q: "No Stupid Questions" },
  { name: "Orthodox Conundrum", status: "Doing", slot: "Weekly", q: "Orthodox Conundrum" },
  { name: "SciShow Tangents", status: "Doing", slot: "Weekly", q: "SciShow Tangents" },
  { name: "SeforimChatter", status: "Doing", slot: "Weekly", q: "SeforimChatter" },
  { name: "Something You Should Know", status: "Doing", slot: "Weekly", q: "Something You Should Know" },
  { name: "StarTalk Radio", status: "Doing", slot: "Weekly", q: "StarTalk Radio" },
  { name: "Stuff You Should Know", status: "Doing", slot: "Weekly", q: "Stuff You Should Know" },
  { name: "TED Radio Hour", status: "Doing", slot: "Weekly", q: "TED Radio Hour" },
  { name: "The Economist Asks", status: "Doing", slot: "Weekly", q: "The Economist Asks", note: "Standalone feed is a 2015 stub - current episodes are published inside Economist Podcasts, so the dates and lengths here are not the live show" },
  { name: "The Mindset Mentor", status: "Doing", slot: "Weekly", q: "The Mindset Mentor" },
  { name: "The Q & A with Rabbi Breitowitz", status: "Doing", slot: "Weekly", q: "Rabbi Breitowitz Q&A" },
  { name: "The School of Greatness", status: "Doing", slot: "Weekly", q: "The School of Greatness" },
  { name: "This American Life", status: "Doing", slot: "Weekly", q: "This American Life" },
  { name: "60-Second Science", status: "Doing", slot: "Weekly", q: "Science Quickly Scientific American", pick: "Science Quickly", note: "Renamed Science Quickly. Sheet: cancel - uncomfortable content" },
  { name: "Radiolab", status: "Doing", slot: "Weekly", q: "Radiolab", note: "Sheet: remove - anti-Israel" },

  // ---- Daily tab: active ----
  { name: "Economist Radio", status: "Doing", slot: "Daily", q: "Economist Podcasts", pick: "Economist Podcasts" },
  { name: "7 Good Minutes Daily Self-Improvement", status: "Doing", slot: "Daily", q: "7 Good Minutes", pick: "7 Good Minutes" },
  { name: "Uncanny Valley (WIRED)", status: "Doing", slot: "Daily", q: "Uncanny Valley WIRED" },
  { name: "TED Talks Daily", status: "Doing", slot: "Daily", q: "TED Talks Daily" },
  { name: "Into the Verse (Aleph Beta)", status: "Doing", slot: "Daily", q: "Into the Verse Aleph Beta" },
  { name: "A Book Like No Other (Aleph Beta)", status: "Doing", slot: "Daily", q: "A Book Like No Other Aleph Beta" },

  // ---- News tab: active ----
  { name: "Curiosity Daily", status: "Doing", slot: "News", q: "Curiosity Daily" },
  { name: "PBS NewsHour - Science", status: "Doing", slot: "News", q: "PBS NewsHour Science" },
  { name: "Forbes Daily Briefing", status: "Doing", slot: "News", q: "Forbes Daily Briefing" },
  { name: "WSJ Minute Briefing", status: "Doing", slot: "News", q: "WSJ Minute Briefing" },
  { name: "Inc. (news brief)", status: "Doing", slot: "News", kind: "News brief" },
  { name: "This Day in History", status: "Doing", slot: "News", q: "This Day in History Class" },
  { name: "Real Simple Tips", status: "Doing", slot: "News", q: "Real Simple Tips" },
  { name: "TechCrunch Startup News", status: "Doing", slot: "News", q: "TechCrunch Startup News" },
  { name: "Fast Company Daily", status: "Doing", slot: "News", kind: "News brief" },
  { name: "WSJ What's News", status: "Doing", slot: "News", q: "WSJ What's News" },
  { name: "The Space", status: "Doing", slot: "News", kind: "News brief" },
  { name: "Inc. Productivity Tip of the Day", status: "Doing", slot: "News", q: "Inc Productivity Tip of the Day" },
  { name: "The Economist Morning Briefing", status: "Doing", slot: "News", kind: "News brief" },
  { name: "Parents Tip of the Day", status: "Doing", slot: "News", kind: "News brief" },
  { name: "WIRED Business", status: "Doing", slot: "News", q: "WIRED Business", pick: "Business, Spoken" },
  { name: "Bloomberg First Word", status: "Doing", slot: "News", kind: "News brief" },
  { name: "Daily Tech Headlines", status: "Doing", slot: "News", q: "Daily Tech Headlines" },
  { name: "Reuters TV (US)", status: "Doing", slot: "News", q: "Reuters World News", pick: "Reuters World News" },
  { name: "ABC News Nightline", status: "Doing", slot: "News", q: "Nightline ABC News", pick: "Nightline" },

  // ---- Considering ----
  { name: "Unconfuse Me with Bill Gates", status: "Considering", slot: "Weekly", q: "Unconfuse Me with Bill Gates" },
  { name: "History for the Curious", status: "Considering", slot: "Weekly", q: "History for the Curious Jewish History" },
  { name: "The WIRED Podcast", status: "Considering", slot: "Weekly", q: "The WIRED Podcast" },
  { name: "WSJ's The Future of Everything", status: "Considering", slot: "Weekly", q: "Bold Names WSJ", pick: "Bold Names", note: "Renamed Bold Names" },
  { name: "Money Talks from Economist Radio", status: "Considering", slot: "Weekly", q: "Money Talks Economist" },
  { name: "Making Sense with Sam Harris", status: "Considering", slot: "Weekly", q: "Making Sense with Sam Harris" },
  { name: "Philosophize This!", status: "Considering", slot: "Weekly", q: "Philosophize This" },
  { name: "The Jordan B. Peterson Podcast", status: "Considering", slot: "Weekly", q: "Jordan B Peterson Podcast" },
  { name: "The Jewish Thought Project", status: "Considering", slot: "Weekly", q: "The Jewish Thought Project" },
  { name: "The Office of Rabbi Sacks", status: "Considering", slot: "Weekly", q: "Rabbi Sacks", pick: "The Rabbi Sacks Legacy" },
  { name: "Breslev Torah Lessons", status: "Considering", slot: "Weekly", q: "Breslev Torah" },
  { name: "Hidden Brain", status: "Considering", slot: "Weekly", q: "Hidden Brain" },
  { name: "Saturday to Shabbos", status: "Considering", slot: "Weekly", q: "Saturday To Shabbos", pick: "Saturday To Shabbos" },
  { name: "Torat Imecha Nach Yomi", status: "Considering", slot: "Weekly", q: "Torat Imecha Nach Yomi" },
  { name: "Torat Imecha Parsha", status: "Considering", slot: "Weekly", q: "Torat Imecha Parsha" },
  { name: "What Does Judaism Say About...?", status: "Considering", slot: "Weekly", q: "What Does Judaism Say About Nachum Amsel" },
  { name: "Tzarich Iyun", status: "Considering", slot: "Weekly", q: "Tzarich Iyun" },
  { name: "Curiosity Weekly", status: "Considering", slot: "Weekly", q: "Curiosity Weekly" },
  { name: "Ask Haviv Anything", status: "Considering", slot: "Weekly", q: "Ask Haviv Anything" },
  { name: "Unpacking Israeli History", status: "Considering", slot: "Weekly", q: "Unpacking Israeli History" },
  { name: "Call Me Back", status: "Considering", slot: "Weekly", q: "Call Me Back Dan Senor" },
  { name: "Parsha Perspectives", status: "Considering", slot: "Weekly", q: "Parsha Perspectives Efrem Goldberg" },
  { name: "Shapell's Virtual Beit Midrash", status: "Considering", slot: "Daily", q: "Shapell Virtual Beit Midrash" },
  { name: "TechStuff", status: "Considering", slot: "Daily", q: "TechStuff" },
  { name: "Consider This from NPR", status: "Considering", slot: "News", q: "Consider This NPR" },

  // ---- Dropped ----
  { name: "Toras Avigdor", status: "Dropped", slot: "Weekly", q: "Toras Avigdor" },
  { name: "Babbage from Economist Radio", status: "Dropped", slot: "Weekly", q: "Babbage Economist", note: "Now paywalled" },
  { name: "Mini Sermon (Rabbi Levi Avtzon)", status: "Dropped", slot: "Weekly", q: "Daily Inspiration Levi Avtzon", pick: "Daily Inspiration With Rabbi Levi Avtzon", note: "Shares one feed with Daily Inspiration; no new episodes" },
  { name: "Daily Inspiration (Rabbi Levi Avtzon)", status: "Dropped", slot: "Weekly", q: "Daily Inspiration Levi Avtzon" },
  { name: "Tanya to Transform", status: "Dropped", slot: "Daily", q: "Tanya to Transform", note: "Spotify-only in Google Home; RSS works in this app" },
  { name: "Daily Tanach", status: "Dropped", slot: "Daily", q: "Daily Tanach", note: "No new episodes" },
  { name: "WIRED Science", status: "Dropped", slot: "Daily", kind: "Discontinued", note: "Sheet: cannot find anymore - no surviving feed" },
  { name: "What's New With WIRED", status: "Dropped", slot: "Daily", kind: "Discontinued", note: "Sheet: cannot find anymore - no surviving feed" },
  { name: "WSJ Tech News Briefing", status: "Dropped", slot: "Daily", q: "WSJ Tech News Briefing", note: "Spotify-only in Google Home; RSS works in this app" },
  { name: "The Intelligence", status: "Dropped", slot: "Daily", q: "The Intelligence Economist" },
  { name: "KMTT - the Torah Podcast", status: "Dropped", slot: "Daily", q: "KMTT Torah Podcast", note: "Hebrew; spotty timing" },
  { name: "Talking Talmud", status: "Dropped", slot: "Daily", q: "Talking Talmud" },
];
